spring:
  profiles:
      active: peer1
---

spring:
  profiles: dev
server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

---
spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
     defaultZone: http://peer2:1112/eureka/
  server:
    enable-self-preservation: false

---
spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/
  server:
    enable-self-preservation: false